name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
    - uses: getong/mariadb-action@v1.1
      with:
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql database: 'test' # Optional, default value is "test". The specified database which will be create
        mysql root password: root # Required if "mysql user" is empty, default is empty. The root superuser password
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "copy('.env.test', '.env');"
    - name: show env
      run: cat .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Update Dependencies ( and lock )
      run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
    - name: Create bootstrap folder
      run: mkdir -p bootstrap/cache 
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: try generating docs
      run: php artisan swagger-lume:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --debug -v